spring:
  profiles:
    include: db, aws, ocr, discord, log
    active: local
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 5MB
  mvc:
    async:
      request-timeout: 3000



server:
  error:
    whitelabel:
      enabled: false