spring:
  profiles:
    include: db, aws, ocr, discord, log
    active: local
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 4MB

server:
  error:
    whitelabel:
      enabled: false