name: CD
on:
  push:
    branches:
      - master
      - config/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: plzprayme/ggiriggiri-config
          token: ${{ secrets.CONFIG_REPOSITORY_TOKEN }}
          path: src/main/resources/config


      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: chmod +x gradlew && ./gradlew build

      - name: 현재 시간 가져오기
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 도커 이미지 빌드 & 푸시
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mashupggiriggiri/server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: |
          cd deploy && zip -r deploy.zip .

      - run: ls

      - name: 배포
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_BEANSTALK_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_BEANSTALK_SECRET_KEY }}
          application_name: ggiriggiri-server
          environment_name: Ggiriggiriserver-env
          version_label: deploy-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ./deploy/deploy.zip
          wait_for_deployment: false
