name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - config/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: plzprayme/ggiriggiri-config
          token: ${{ secrets.CONFIG_REPOSITORY_TOKEN }}
          path: src/main/resources/config

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - run: chmod +x gradlew && ./gradlew build